import { View, Text, Image, TouchableOpacity} from 'react-native';
import React, {useState} from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import { TextInput } from 'react-native-gesture-handler';
import { FontAwesome5 } from '@expo/vector-icons';


const PayBill = ({ navigation }) => {
   const [shopNumber, setShopNumber]=useState(0);

    GenerateRandomNumber=()=>
    {
    
    var RandomNumber = Math.floor(Math.random() * 1000000) + 1 ;
    
    setShopNumber(RandomNumber)
    };

    useState(()=>{
        GenerateRandomNumber()
    },[]);

    

  return (
    <SafeAreaView style={{ flex:1, backgroundColor:'#fff'}}>
   
    <View style={{ alignItems:'center'}}>
        <View>
            <Text style={{ fontSize:27, fontWeight:'700', color:"#000", marginTop:20, marginBottom:5}}>
                Complete Your
            </Text>
            <Text style={{ fontSize:27, fontWeight:'700', color:"#000", marginBottom:20, color:'#5AB500'}}>
                Personal Profile📝
            </Text>
            <Text>Kindly Fill in the details to personalize the application</Text>
        </View>
    </View>
    <View style={{paddingHorizontal:30, marginTop:40}}>
       <TextInput
       
        placeholder='Full Name'
        style={{ borderBottomColor:'black', borderBottomWidth:1, padding:10}}
       />
       
      
    </View>
    <View style={{paddingHorizontal:30, marginTop:20}}>
       <TextInput
        placeholder='Phone Number'
        style={{ borderBottomColor:'black', borderBottomWidth:1, padding:10}}
       />
     </View>

     <View style={{paddingHorizontal:30, marginTop:20}}>
       <TextInput
        placeholder='Shop Code'
        keyboardType='numeric'
        value={shopNumber.toString()}
        style={{ borderBottomColor:'black', borderBottomWidth:1, padding:10, color:'red', fontWeight:'bold', fontSize:20}}
       />
       <Text style={{ marginTop:20}}>This should be autogenerated</Text>
       <FontAwesome5 name="copy" size={24} color="black" />
     </View>
   
   <View style={{flex:1, justifyContent:'flex-end', marginBottom:30}}>
        
        <TouchableOpacity onPress={()=>navigation.navigate('Profile1')} style={{ justifyContent:'center', alignItems:'center', backgroundColor:'#5AB500', width:'80%', height:50, borderRadius:48, marginTop:40, alignSelf:'center'}}>
                <Text style={{ color:'#fff', fontSize:24, fontWeight:'700'}}>Continue</Text>
        </TouchableOpacity>
    </View>
    </SafeAreaView>
  )
}

export default PayBill;